server:
  error:
    whitelabel:
      enabled: false
spring:
  config:
    activate:
      on-profile:
        - production
  devtools:
    restart:
      enabled: true
  docker:
    compose:
      file: ./compose.yml
  messages:
    basename: locales/message
  data:
    mongodb:
      database: vault
      host: locallhost
      port: 27017
      uuid-representation: standard
    redis:
      database: 0
      host: localhost
      port: 6379
      password: secret
      timeout: 60000
logging:
  level:
    root: WARN
    com:
      securevault:
        main:
          service: INFO
    org:
      springframework:
        security: debug
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
api:
  uri-prefix: /api
app:
  pbkdf2:
    secret: ==========Secure=PBKDF2=Vault===========
    salt-length: 600000
    iterations: 256
  jwt:
    secret: ==============Secure=Vault==============
    token:
      expires-in: "#{60 * 60 * 1000}"
    refresh-token:
      expires-in: "#{24 * 60 * 60 * 1000}"
    remember-me:
      expires-in: "#{24 * 60 * 60 * 1000 * 7}"
cookie:
  refresh:
    domain: "localhost"
    path: "/api/v1/auth"
    sameSite: "strict"
    httpOnly: true
    secure: true
