server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: ${APP_NAME}
  config:
    import: env.properties
    activate:
      on-profile:
        - production
  devtools:
    restart:
      enabled: true
  docker:
    compose:
      file: ./compose.yml
  messages:
    basename: locales/message
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}
      uuid-representation: standard
    redis:
      database: ${REDIS_DATABASE}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: false
          tls:
            enable: true
          starttls:
            enable: true

logging:
  level:
    root: WARN
    com:
      securevault:
        main: INFO
        main.service: INFO
        main.controller: INFO
        main.util: INFO
    org:
      springframework:
        security: WARN
        web: WARN
        data: WARN
        mail: INFO
    mongodb: WARN
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){magenta} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"
  file:
    name: logs/secure-vault.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100MB

api:
  uri-prefix: ${API_URI_PREFIX}

app:
  pbkdf2:
    secret: ${PBKDF2_SECRET}
    salt-length: ${PBKDF2_SALT_LENGTH}
    iterations: ${PBKDF2_ITERATIONS}
  jwt:
    secret: ${JWT_SECRET}
    token:
      expires-in: ${JWT_TOKEN_EXPIRES_IN}
    refresh-token:
      expires-in: ${JWT_REFRESH_TOKEN_EXPIRES_IN}
    remember-me:
      expires-in: ${JWT_REMEMBER_ME_EXPIRES_IN}
  registration:
    email:
      token:
        expires-in: ${REGISTRATION_EMAIL_TOKEN_EXPIRES_IN}
  url: ${SERVER_URL}
  frontend-url: ${FRONTEND_URL}

cookie:
  refresh:
    domain: ${COOKIE_REFRESH_DOMAIN}
    path: ${COOKIE_REFRESH_PATH}
    sameSite: ${COOKIE_REFRESH_SAME_SITE}
    httpOnly: true
    secure: false
