package com.securevault.main.enums;

public enum ErrorCode {
    INVALID_REQUEST,
    RESOURCE_NOT_FOUND,
    RESOURCE_EXISTS,
    UNAUTHORIZED,
    FORBIDDEN,
    BAD_REQUEST,
    CONFLICT,
    UNPROCESSABLE_ENTITY,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE
}
